make original filename available to the  onFileLoad callback
corpix/material-ui-upload pull request #4
Opened 2017-06-04 11:33 UTC by jorgemmsilva

2017-06-10 22:19 UTC, corpix requested changes

2017-06-10 22:19 UTC, corpix commented on src/Upload/index.js
> +                    reader.fileName = file.name
Why we should define a custom property on `FileReader`? Why not wrap the `this.props.onFileLoad` like this?
``` javascript
reader.onload = (e) => this.props.onFileLoad(e, file);
```

2017-06-11 17:09 UTC, jorgemmsilva commented
so you can do something like this:
`
  onFileLoad = (e) => {
      this.setState({
        newFileData: e.target.result,
        newFileName: e.target.name,
      })
  }
`

2017-06-12 03:50 UTC, corpix commented
It is ok to have a file name in the `onFileLoad` handler, but it is bad to define it directly on `FileReader` instance, you should not modify browser-providen things and things around. The more clean solution is to define additional argument for a handler. At this moment we have `e` in `onFileLoad`, now we need a file name too, so we could wrap `onFileLoad` in this way

``` javascript
reader.onload = (e) => this.props.onFileLoad(e, file);
```

So code in your example will look like this:

``` javascript
    onFileLoad = (e, file) => {
      this.setState({
        newFileData: e.target.result,
        newFileName: file.name,
      })
    }
```

2017-06-12 16:47 UTC, jorgemmsilva commented
I was thinking about simplicity for the end user... But I do get your point about modifying native objects :p

updated

2017-06-12 21:39 UTC, merged

2017-06-12 21:39 UTC, corpix commented
Thank you